name: Issue Greeting Bot

on:
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    
    steps:
      - name: Add greeting comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Hello! Thank you for creating this issue.\n\nWe will review it and get back to you soon.'
            })
